import {
  InformasiDesaPage,
  TambahInformasiDesa,
  BeritaPage,
  AddNews,
  UpdateNewsPage,
  LaporanMasyarakatPage,
  BpdForumPage as BUMDesForumPage,
  BumdesRegistration,
  AddBumdes,
  AddPengajuanMitraBumdes,
  PengajuanMitraBumdes,
  KategoriBumdes,
  WisataBumdes,
  ProdukBumdes,
  UlasanBumdes,
  TransaksiBumdes,
  GrafikAgama,
  GrafikDisabilitas,
  GrafikGolonganDarah,
  GrafikInfo,
  GrafikJenisKelamin,
  GrafikKewarganegaraan,
  GrafikPekerjaan,
  GrafikPendidikan,
  GrafikRtRw,
  GrafikStatusPerkawinan,
  GrafikUsia,
  DashboardPage,
  PenarikanInvestasiBumdes,
  PermintaanInvestasiBumdes,
  InvestmentBumdes,
  DetailInvestment,
  BUMDesPPOB,
} from "../pages";

export const routes = [
  {
    path: "/dashboard",
    component: DashboardPage,
    name: "Informasi Desa",
    layout: "/bumdes",
  },
  //informasi-desa
  {
    path: "/informasi-desa",
    component: InformasiDesaPage,
    name: "Informasi Desa",
    layout: "/bumdes",
  },
  {
    path: "/informasi-desa/add",
    component: TambahInformasiDesa,
    name: "Informasi Desa",
    layout: "/bumdes",
  },
  {
    path: "/berita",
    component: BeritaPage,
    name: "berita",
    layout: "/bumdes",
  },
  {
    path: "/berita/add",
    component: AddNews,
    name: "berita",
    layout: "/bumdes",
  },
  {
    path: "/berita/update/:id",
    component: UpdateNewsPage,
    name: "berita",
    layout: "/bumdes",
  },
  {
    path: "/laporan-masyarakat",
    component: LaporanMasyarakatPage,
    name: "Laporan Masyarakat",
    layout: "/bumdes",
  },
  {
    path: "/forum-masyarakat",
    component: BUMDesForumPage,
    name: "simple-forum",
    layout: "/bumdes",
  },

  //bumdes
  {
    path: "/daftar-mitra",
    component: BumdesRegistration,
    name: "Daftar Mitra Bumdes",
    layout: "/bumdes",
  },
  {
    path: "/daftar-mitra/add",
    component: AddBumdes,
    name: "Add Mitra Bumdes",
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/pengajuan-mitra",
    component: PengajuanMitraBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/pengajuan-mitra/add/",
    component: AddBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/pengajuan-mitra/add/:id",
    component: AddPengajuanMitraBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/kategori",
    component: KategoriBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/wisata",
    component: WisataBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/produk",
    component: ProdukBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/transaksi",
    component: TransaksiBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/ulasan",
    component: UlasanBumdes,
    layout: "/bumdes",
    exact: true,
  },
  {
    path: "/ppob",
    component: BUMDesPPOB,
    name: "PPOB",
    layout: "/bumdes",
  },
  // {
  //   path: "/riwayat-transaksi",
  //   component: () => <h1>Sedang Dalam Pengembangan</h1>,
  //   name: "Riwayat Transaksi",
  //   layout: "/bumdes",
  // },

  // investasi
  {
    path: "/permintaan",
    component: PermintaanInvestasiBumdes,
    layout: "/bumdes",
  },
  {
    path: "/investment",
    component: InvestmentBumdes,
    layout: "/bumdes",
  },
  {
    path: "/investment/detail/:id",
    component: DetailInvestment,
    layout: "/bumdes",
  },
  {
    path: "/penarikan",
    component: PenarikanInvestasiBumdes,
    layout: "/bumdes",
  },

  //grafik
  {
    path: "/jenis-kelamin",
    component: GrafikJenisKelamin,
    name: "Jenis Kelamin",
    layout: "/bumdes",
  },
  {
    path: "/grafik-usia",
    component: GrafikUsia,
    name: "Usia",
    layout: "/bumdes",
  },
  {
    path: "/pendidikan",
    component: GrafikPendidikan,
    name: "Pendidikan",
    layout: "/bumdes",
  },
  {
    path: "/agama",
    component: GrafikAgama,
    name: "Pendidikan",
    layout: "/bumdes",
  },
  {
    path: "/pekerjaan",
    component: GrafikPekerjaan,
    name: "Pekerjaan",
    layout: "/bumdes",
  },
  {
    path: "/kewarganegaraan",
    component: GrafikKewarganegaraan,
    name: "Kewarganegaraan",
    layout: "/bumdes",
  },
  {
    path: "/golongan-darah",
    component: GrafikGolonganDarah,
    name: "Golongan Darah",
    layout: "/bumdes",
  },
  {
    path: "/disabilitas",
    component: GrafikDisabilitas,
    name: "Disabilitas",
    layout: "/bumdes",
  },
  {
    path: "/status-perkawinan",
    component: GrafikStatusPerkawinan,
    name: "Status Perkawinan",
    layout: "/bumdes",
  },
  {
    path: "/rt-rw",
    component: GrafikRtRw,
    name: "RT-RW",
    layout: "/bumdes",
  },
];
