import {
  AddNews,
  DashboardPage,
  DataWargaPage,
  DataWargaDetail,
  AddDataWarga,
  BeritaPage,
  UserDashboard,
  ProfileDashboard,
  ActiveUserStatistic,
  ActiveUserWarga,
  ActiveUserVerification,
  GrafikPage,
  TipeLaporanPage,
  ActivityHistory,
  AddUserDashboard,
  LaporPemdes,
  LaporSurat,
  SimpleForum,
  SaldoPage,
  MitraBumdes,
  BloodNeed,
  BloodProvider,
  BloodStock,
  DonorSchedule,
  DonorList,
  BloodReport,
  DataInfo,
  AddDataInfo,
  ExpenseData,
  FinancingData,
  IncomeData,
  ProfileData,
  GrafikInfo,
  SuratKelahiranPage,
  SuratKematianPage,
  SuratTugasPerintahPage,
  BuatSuratPage,
  DatalayananSuratPage,
  Fundraising,
  DonationCategory,
  FundraisingWarga,
  FundraisingDesa,
  AddFundraisingDesa,
  BedaIdentitasPage,
  SuratKeteranganBepergianPage,
  SuratKeteranganDomisiliPage,
  SuratKeteranganDomisiliLemabagaPage,
  SuratKeteranganDomisiliNonWargaPage,
  SuratKeteranganDomisiliPerusahaanPage,
  SuratKeteranganDomisiliPerusahaanNonWargaPage,
  SuratKeteranganDudaJandaPage,
  SuratKeteranganGhaibPage,
  SuratKeteranganAlpaPage,
  PembayaranPage,
  SuratKeteranganResiKtpPage,
  SuratKeteranganStatusPerkawinan,
  SuratKeteranganUsahaPage,
  SuratKeteranganUsahaNonWargaPage,
  SuratKuasaPage,
  LaporanMasyarakatPage,
  SuratPengantarKehilanganPage,
  SuratRekomendasiIzinKeramaianPage,
  SuratPengantarPerkawinanPage,
  SuratPengantarPerkawinanPriaPage,
  GrafikJenisKelamin,
  GrafikUsia,
  GrafikPendidikan,
  GrafikAgama,
  GrafikPekerjaan,
  GrafikKewarganegaraan,
  GrafikGolonganDarah,
  GrafikDisabilitas,
  GrafikStatusPerkawinan,
  GrafikRtRw,
  PengajuanIDesaPage,
  ListBuatSurat,
  SuratTugasPerintah,
  BumdesRegistration,
  AddBumdes,
  InformasiDesa,
  TambahInformasiDesa,
  PendukungDesa,
  DonorDarahPage,
} from "../pages";

export const routes = [
  {
    path: "/saldo",
    component: SaldoPage,
    name: "Saldo",
    layout: "/private",
  },
  {
    path: "/dashboard",
    component: DashboardPage,
    name: "dashboard",
    layout: "/private",
  },
  {
    path: "/profile-dashboard",
    component: ProfileDashboard,
    name: "profile-dashboard",
    layout: "/private",
  },

  {
    path: "/data-warga",
    component: DataWargaPage,
    name: "datawarga",
    layout: "/private",
  },
  {
    path: "/data-warga/edit/:id",
    component: DataWargaDetail,
    name: "dataWargaDetail",
    layout: "/private",
  },
  {
    path: "/data-warga/add",
    component: AddDataWarga,
    name: "AddDataWarga",
    layout: "/private",
    exact: true,
  },
  {
    path: "/user-dashboard",
    component: UserDashboard,
    name: "user-dashboard",
    layout: "/private",
  },
  {
    path: "/user-dashboard/add",
    component: AddUserDashboard,
    name: "AddUserDashboard",
    layout: "/private",
  },
  {
    path: "/kop-surat",
    component: LaporPemdes,
    name: "kop-surat",
    layout: "/private",
  },
  {
    path: "/berita",
    component: BeritaPage,
    name: "berita",
    layout: "/private",
  },
  {
    path: "/berita/add",
    component: AddNews,
    name: "berita",
    layout: "/private",
  },
  {
    path: "/info",
    component: DataInfo,
    name: "Info",
    layout: "/private",
  },
  {
    path: "/info/add",
    component: AddDataInfo,
    name: "Add Info",
    layout: "/private",
    exact: true,
  },
  {
    path: "/info-grafik",
    component: GrafikInfo,
    name: "Info Grafik",
    layout: "/private",
  },
  {
    path: "/info-expense",
    component: ExpenseData,
    name: "Info Expense",
    layout: "/private",
  },
  {
    path: "/info-financing",
    component: FinancingData,
    name: "Info Financing",
    layout: "/private",
  },
  {
    path: "/info-income",
    component: IncomeData,
    name: "Info Income",
    layout: "/private",
  },
  {
    path: "/info-profile",
    component: ProfileData,
    name: "Info Profile",
    layout: "/private",
  },
  {
    path: "/mitra-bumdes",
    component: MitraBumdes,
    name: "Mitra Bumdes",
    layout: "/private",
  },

  {
    path: "/surat-keterangan-kelahiran",
    component: SuratKelahiranPage,
    name: "jenis-keeterangan-kelahiran",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-kematian",
    component: SuratKematianPage,
    name: "surat-keterangan-kematian",
    layout: "/private",
  },
  {
    path: "/surat-tugas-perintah",
    component: SuratTugasPerintahPage,
    name: "surat-tugas-perintah",
    layout: "/private",
  },
  {
    path: "/surat-beda-identitas",
    component: BedaIdentitasPage,
    name: "surat-beda-identitas",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-bepergian",
    component: SuratKeteranganBepergianPage,
    name: "surat-keterangan-bepergian",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-domisili",
    component: SuratKeteranganDomisiliPage,
    name: "surat-keterangan-domisili",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-domisili-lembaga",
    component: SuratKeteranganDomisiliLemabagaPage,
    name: "surat-keterangan-domisili-lembaga",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-domisili-non-warga",
    component: SuratKeteranganDomisiliNonWargaPage,
    name: "surat-keterangan-domisili-non-warga",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-domisili-perusahaan",
    component: SuratKeteranganDomisiliPerusahaanPage,
    name: "surat-keterangan-domisili-perusahaan",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-domisili-perusahaan-non-warga",
    component: SuratKeteranganDomisiliPerusahaanNonWargaPage,
    name: "surat-keterangan-domisili-perusahaan-non-warga",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-duda-janda",
    component: SuratKeteranganDudaJandaPage,
    name: "surat-keterangan-duda-janda",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-ghaib",
    component: SuratKeteranganGhaibPage,
    name: "surat-keterangan-ghaib",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-alpa",
    component: SuratKeteranganAlpaPage,
    name: "surat-keterangan-alpa",
    layout: "/private",
  },
  {
    path: "/usia",
    component: "",
    name: "usia",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-resi-ktp-sementara",
    component: SuratKeteranganResiKtpPage,
    name: "Surat Keterangan Resi KTP Sementara",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-status-perkawinan",
    component: SuratKeteranganStatusPerkawinan,
    name: "Surat Keterangan STatus Perkawinan",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-usaha",
    component: SuratKeteranganUsahaPage,
    name: "Surat Keterangan Usaha",
    layout: "/private",
  },
  {
    path: "/surat-keterangan-usaha-non-warga",
    component: SuratKeteranganUsahaNonWargaPage,
    name: "SUrat Keterangan Usaha Non Warga",
    layout: "/private",
  },
  {
    path: "/surat-kuasa",
    component: SuratKuasaPage,
    name: "Surat Kuasa",
    layout: "/private",
  },
  {
    path: "/laporan-masyarakat",
    component: LaporanMasyarakatPage,
    name: "Laporan Masyarakat",
    layout: "/private",
  },
  {
    path: "/surat-pengantar-kehilangan",
    component: SuratPengantarKehilanganPage,
    name: "Surat Pengantar Kehilangan",
    layout: "/private",
  },
  {
    path: "/surat-rekomendasi-izin-keramaian",
    component: SuratRekomendasiIzinKeramaianPage,
    name: "Surat Rekomendasi Izin Keramaian",
    layout: "/private",
  },
  {
    path: "/surat-pengantar-perkawinan",
    component: SuratPengantarPerkawinanPage,
    name: "Surat Pengantar Perkawinan Pria",
    layout: "/private",
  },
  {
    path: "/surat-pengantar-perkawinan-pria",
    component: SuratPengantarPerkawinanPriaPage,
    name: "Surat Pengantar Perkawinan Pria",
    layout: "/private",
  },
  {
    path: "/surat-rekomendasi-izin-keramaian",
    component: SuratPengantarPerkawinanPriaPage,
    name: "Surat Pengantar Perkawinan Pria",
    layout: "/private",
  },
  {
    path: "/forum-masyarakat",
    component: SimpleForum,
    name: "simple-forum",
    layout: "/private",
  },
  {
    path: "/aktifitas-anggota",
    component: ActivityHistory,
    name: "riwayat-aktifitas",
    layout: "/private",
  },
  {
    path: "/active-user-statistic",
    component: ActiveUserStatistic,
    name: "active-user-statistic",
    layout: "/private",
  },
  {
    path: "/active-user-warga",
    component: ActiveUserWarga,
    name: "active-user-warga",
    layout: "/private",
  },
  {
    path: "/active-user-verifikasi",
    component: ActiveUserVerification,
    name: "active-user-verifikasi",
    layout: "/private",
  },
  {
    path: "/grafik-laporan",
    component: GrafikPage,
    name: "active-user-verifikasi",
    layout: "/private",
  },
  {
    path: "/tipe-laporan",
    component: TipeLaporanPage,
    name: "Tipe Laporan",
    layout: "/private",
  },
  {
    path: "/blood-need",
    component: BloodNeed,
    name: "Butuh Darah",
    layout: "/private",
  },
  {
    path: "/blood-provider",
    component: BloodProvider,
    name: "Provider Darah",
    layout: "/private",
  },
  {
    path: "/blood-stock",
    component: BloodStock,
    name: "Stock Darah",
    layout: "/private",
  },
  {
    path: "/donor-schedule",
    component: DonorSchedule,
    name: "Jadwal Donor",
    layout: "/private",
  },
  {
    path: "/blood-report",
    component: BloodReport,
    name: "Report Darah",
    layout: "/private",
  },
  {
    path: "/blood-donors",
    component: DonorList,
    name: "Pendonor",
    layout: "/private",
  },
  {
    path: "/buat-surat",
    component: BuatSuratPage,
    name: "buat-surat",
    layout: "/private",
  },
  {
    path: "/data-layanan-surat",
    component: DatalayananSuratPage,
    name: "data-layanan-surat",
    layout: "/private",
  },
  {
    path: "/donation-category",
    component: DonationCategory,
    name: "DonationCategory",
    layout: "/private",
  },
  {
    path: "/fundraising",
    component: Fundraising,
    name: "Fundraising",
    layout: "/private",
  },
  {
    path: "/fundraising-warga",
    component: FundraisingWarga,
    name: "Fundraising Warga",
    layout: "/private",
  },
  {
    path: "/fundraising-desa",
    component: FundraisingDesa,
    name: "Fundraising Desa",
    layout: "/private",
  },
  {
    path: "/fundraising-desa/add",
    component: AddFundraisingDesa,
    name: "Add Fundraising Desa",
    layout: "/private",
  },
  {
    path: "/pembayaran",
    component: PembayaranPage,
    name: "pembayaran",
    layout: "/private",
  },
  {
    path: "/jenis-kelamin",
    component: GrafikJenisKelamin,
    name: "Jenis Kelamin",
    layout: "/private",
  },
  {
    path: "/grafik-usia",
    component: GrafikUsia,
    name: "Usia",
    layout: "/private",
  },
  {
    path: "/pendidikan",
    component: GrafikPendidikan,
    name: "Pendidikan",
    layout: "/private",
  },
  {
    path: "/agama",
    component: GrafikAgama,
    name: "Pendidikan",
    layout: "/private",
  },
  {
    path: "/pekerjaan",
    component: GrafikPekerjaan,
    name: "Pekerjaan",
    layout: "/private",
  },
  {
    path: "/kewarganegaraan",
    component: GrafikKewarganegaraan,
    name: "Kewarganegaraan",
    layout: "/private",
  },
  {
    path: "/golongan-darah",
    component: GrafikGolonganDarah,
    name: "Golongan Darah",
    layout: "/private",
  },
  {
    path: "/disabilitas",
    component: GrafikDisabilitas,
    name: "Disabilitas",
    layout: "/private",
  },
  {
    path: "/status-perkawinan",
    component: GrafikStatusPerkawinan,
    name: "Status Perkawinan",
    layout: "/private",
  },
  {
    path: "/rt-rw",
    component: GrafikRtRw,
    name: "RT-RW",
    layout: "/private",
  },
  {
    path: "/pengajuan-idesa",
    component: PengajuanIDesaPage,
    name: "Pengajuan E-Desa",
    layout: "/private",
  },
  {
    path: "/pengajuan-idesa/list",
    component: ListBuatSurat,
    name: "list Pengajuan E-Desa",
    layout: "/private",
  },
  {
    path: "/pengajuan-idesa/list/surat-tugas-perintah",
    component: SuratTugasPerintah,
    name: "Surat Tugas/perintah E-Desa",
    layout: "/private",
  },
  {
    path: "/daftar-mitra",
    component: BumdesRegistration,
    name: "Daftar Mitra Bumdes",
    layout: "/private",
  },
  {
    path: "/daftar-mitra/add",
    component: AddBumdes,
    name: "Add Mitra Bumdes",
    layout: "/private",
    exact: true,
  },
  {
    path: "/informasi-desa/add",
    component: TambahInformasiDesa,
    name: "Informasi Desa",
    layout: "/private",
  },
  {
    path: "/informasi-desa/",
    component: InformasiDesa,
    name: "Informasi Desa",
    layout: "/private",
  },
  {
    path: "/pengajuan-edesa",
    component: () => <h1>Sedang Dalam Pengembangan</h1>,
    name: "Pengajuan E-desa",
    layout: "/private",
  },
  {
    path: "/template-surat",
    component: LaporSurat,
    name: "Template Surat",
    layout: "/private",
  },
  {
    path: "/pendukung-desa",
    component: PendukungDesa,
    name: "Pendukung Desa",
    layout: "/private",
  },
  {
    path: "/donor-darah",
    component: DonorDarahPage,
    name: "Template Surat",
    layout: "/private",
  },
  {
    path: "/ppob",
    component: () => <h1>Sedang Dalam Pengembangan</h1>,
    name: "PPOB",
    layout: "/private",
  },
  {
    path: "/riwayat-transaksi",
    component: () => <h1>Sedang Dalam Pengembangan</h1>,
    name: "Riwayat Transaksi",
    layout: "/private",
  },
  {
    path: "/pengajuan-mitra",
    component: () => <h1>Sedang Dalam Pengembangan</h1>,
    name: "Pengajuan Mitra",
    layout: "/private",
  },
];
