import {
  DashboardSuperAdminPage,
  InvoicePage,
  FaqPage,
  AddFaq,
  RiwayatTransaki,
  DetailRiwayatTransaksi,
  PpobPage,
  TambahPpob,
  EditPpob,
  TransaksiPage,
  TambahTransaksi,
  EditTransaksi,
  PembagianPage,
  TambahPembagian,
  EditPembagian,
  AkunJurnal,
  EditAkunJurnal,
  TambahAkunJurnal
} from "../pages";

export const routes = [
  {
    path: "/dashboard",
    component: DashboardSuperAdminPage,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/invoice",
    component: InvoicePage,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/admin-faq",
    component: FaqPage,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/admin-faq/add",
    component: AddFaq,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/riwayat-transaksi",
    component: RiwayatTransaki,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/riwayat-transaksi/:id",
    component: DetailRiwayatTransaksi,
    name: "dashboard",
    layout: "/super-admin",
  },
  {
    path: "/ppob",
    component: PpobPage,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/ppob/edit/:id",
    component: EditPpob,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/ppob/add",
    component: TambahPpob,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },

  {
    path: "/transaksi",
    component: TransaksiPage,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/transaksi/edit/:id",
    component: EditTransaksi,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/transaksi/add",
    component: TambahTransaksi,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/pembagian",
    component: PembagianPage,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/pembagian/edit/:id",
    component: EditPembagian,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/pembagian/add",
    component: TambahPembagian,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/akun-jurnal",
    component: AkunJurnal,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/akun-jurnal/edit/:id",
    component:EditAkunJurnal,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
  {
    path: "/akun-jurnal/add",
    component: TambahAkunJurnal,
    name: "dashboard",
    layout: "/super-admin",
    exact: true,
  },
];
