export const TABLE_HEADER = [
  "#",
  "PESANAN",
  "WAKTU",
  "PELANGGAN",
  "STATUS PEMBAYARAN",
  "TOTAL",
  "STATUS PESANAN",
  "TIPE PESANAN",
  "AKSI",
];
export const TABLE_DATA = [
  {
    _id: 1232,
    "#": 1,
    PESANAN: 1232,
    WAKTU: "2022-01-12T03:57:24.150Z",
    PELANGGAN: "Rara Sekar",
    "STATUS PEMBAYARAN": "Belum Dibayar",
    TOTAL: "Rp75.000",
    "STATUS PESANAN": "Diterima",
    "TIPE PESANAN": "Bawa Pulang",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 2291,
    "#": 2,
    PESANAN: 2291,
    WAKTU: "2022-01-11T02:07:31.236Z",
    PELANGGAN: "Jajang Nurjangjang",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp117.500",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 3376,
    "#": 3,
    PESANAN: 3376,
    WAKTU: "2021-12-20T13:20:00.000Z",
    PELANGGAN: "Muhammad Atep",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp20.000",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 5912,
    "#": 4,
    PESANAN: 5912,
    WAKTU: "2021-08-18T03:20:00.000Z",
    PELANGGAN: "Neneng Karneli",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp54.300",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Bawa Pulang",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 1125,
    "#": 5,
    PESANAN: 1125,
    WAKTU: "2021-11-05T02:59:00.000Z",
    PELANGGAN: "Itoch Tochija",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp29.800",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Bawa Pulang",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 9812,
    "#": 6,
    PESANAN: 9812,
    WAKTU: "2021-12-05T02:59:00.000Z",
    PELANGGAN: "Ridwan Kamil",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp40.000",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 7565,
    "#": 7,
    PESANAN: 7565,
    WAKTU: "2021-12-05T02:59:00.000Z",
    PELANGGAN: "Cicih Miricih",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp50.000",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 4456,
    "#": 8,
    PESANAN: 4456,
    WAKTU: "2021-12-05T02:59:00.000Z",
    PELANGGAN: "Annisa Miranti",
    "STATUS PEMBAYARAN": "Dibayar",
    TOTAL: "Rp66.000",
    "STATUS PESANAN": "Terkirim",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 2278,
    "#": 9,
    PESANAN: 2278,
    WAKTU: "2022-01-19T13:40:00.000Z",
    PELANGGAN: "Hana Barbara",
    "STATUS PEMBAYARAN": "Belum Dibayar",
    TOTAL: "Rp80.000",
    "STATUS PESANAN": "Diterima",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
  {
    _id: 8934,
    "#": 10,
    PESANAN: 8934,
    WAKTU: "2022-01-20T13:40:00.000Z",
    PELANGGAN: "Richard Aliando",
    "STATUS PEMBAYARAN": "Belum Dibayar",
    TOTAL: "Rp100.000",
    "STATUS PESANAN": "Diterima",
    "TIPE PESANAN": "Diantarkan",
    AKSI: ["read", "downloadfaktur"],
  },
];
